const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Plugins.NinePatch,
		C3.Plugins.AJAX,
		C3.Plugins.TextBox,
		C3.Plugins.Dictionary,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.TextBox.Acts.SetFocus,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.int,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.System.Exps.trim,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TextBox.Cnds.IsFocused,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.len,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.TextBox.Acts.SetBlur,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.IsTouchingObject
	];
};
self.C3_JsPropNameTable = [
	{IsClothes: 0},
	{Bullet: 0},
	{Sine: 0},
	{Bomber: 0},
	{CargoPants: 0},
	{DenimPants: 0},
	{KnitTee: 0},
	{Polo: 0},
	{Sandals: 0},
	{Socks: 0},
	{Solid: 0},
	{Ground: 0},
	{Active: 0},
	{Platform: 0},
	{Player: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Runner: 0},
	{Spawner: 0},
	{Flyer: 0},
	{ResetButton: 0},
	{Text: 0},
	{TimerText: 0},
	{Rcycl: 0},
	{ScorText: 0},
	{Audio: 0},
	{SpriteClothingLine: 0},
	{Touch: 0},
	{Sprite2: 0},
	{Fade: 0},
	{TiledBackground3: 0},
	{Sprite3: 0},
	{PlayerDog: 0},
	{ChooseHumanBtn1: 0},
	{ChooseDogBtn1: 0},
	{RunnerHuman: 0},
	{StartMarker: 0},
	{ChooseHumanBtn: 0},
	{ChooseDogBtn: 0},
	{BigTextBoxBlue: 0},
	{"9patch": 0},
	{ChezaBtnBG: 0},
	{ChezaBtnText: 0},
	{MainMenuBG: 0},
	{MainMenuText: 0},
	{MuteBtn: 0},
	{MMContainer: 0},
	{MainMenuBG2: 0},
	{Text2: 0},
	{easy: 0},
	{hard: 0},
	{ClockBtn: 0},
	{TiledBackground4: 0},
	{AJAX: 0},
	{TextInput: 0},
	{HighScoreText: 0},
	{Dictionary: 0},
	{SoundtrackByAgentMgumbe: 0},
	{SpriteRope2: 0},
	{SpriteRope3: 0},
	{Loader: 0},
	{DebugText: 0},
	{InstructionText: 0},
	{ClothesTip: 0},
	{ObstacleFamily: 0},
	{Hero: 0},
	{Family1: 0},
	{ObstacleNum: 0},
	{DifficultyScale: 0},
	{SpeedIncrease: 0},
	{TimerVar: 0},
	{CanRestart: 0},
	{Score: 0},
	{ClothingChoice: 0},
	{SelectedHero: 0},
	{FirstTimePlayer: 0},
	{FirstTimeClothes: 0},
	{IsMuted: 0},
	{IsNight: 0},
	{PlayerName: 0},
	{CurrentGameMusic: 0},
	{Started: 0},
	{MenuSong: 0}
];

self.InstanceType = {
	Bomber: class extends self.ISpriteInstance {},
	CargoPants: class extends self.ISpriteInstance {},
	DenimPants: class extends self.ISpriteInstance {},
	KnitTee: class extends self.ISpriteInstance {},
	Polo: class extends self.ISpriteInstance {},
	Sandals: class extends self.ISpriteInstance {},
	Socks: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Runner: class extends self.ISpriteInstance {},
	Spawner: class extends self.ISpriteInstance {},
	Flyer: class extends self.ISpriteInstance {},
	ResetButton: class extends self.IButtonInstance {},
	Text: class extends self.ITextInstance {},
	TimerText: class extends self.ITextInstance {},
	Rcycl: class extends self.ISpriteInstance {},
	ScorText: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	SpriteClothingLine: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	PlayerDog: class extends self.ISpriteInstance {},
	ChooseHumanBtn1: class extends self.IButtonInstance {},
	ChooseDogBtn1: class extends self.IButtonInstance {},
	RunnerHuman: class extends self.ISpriteInstance {},
	StartMarker: class extends self.ISpriteInstance {},
	ChooseHumanBtn: class extends self.ISpriteInstance {},
	ChooseDogBtn: class extends self.ISpriteInstance {},
	BigTextBoxBlue: class extends self.ISpriteInstance {},
	_9patch: class extends self.I9PatchInstance {},
	ChezaBtnBG: class extends self.ISpriteInstance {},
	ChezaBtnText: class extends self.ITextInstance {},
	MainMenuBG: class extends self.ISpriteInstance {},
	MainMenuText: class extends self.ITextInstance {},
	MuteBtn: class extends self.ISpriteInstance {},
	MMContainer: class extends self.ISpriteInstance {},
	MainMenuBG2: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	easy: class extends self.ISpriteInstance {},
	hard: class extends self.ISpriteInstance {},
	ClockBtn: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	AJAX: class extends self.IInstance {},
	TextInput: class extends self.ITextInputInstance {},
	HighScoreText: class extends self.ITextInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	SoundtrackByAgentMgumbe: class extends self.ITextInstance {},
	SpriteRope2: class extends self.ISpriteInstance {},
	SpriteRope3: class extends self.ISpriteInstance {},
	Loader: class extends self.ITextInstance {},
	DebugText: class extends self.ITextInstance {},
	InstructionText: class extends self.ITextInstance {},
	ClothesTip: class extends self.ITextInstance {},
	ObstacleFamily: class extends self.ISpriteInstance {},
	Hero: class extends self.ISpriteInstance {},
	Family1: class extends self.I9PatchInstance {}
}